### ISSUE TITLE
An error occurred while installing autopy3

### ISSUE THREAD

**Issue by ganziqim** [msanders/autopy#101] opened 2017-12-19 08:43 UTC
Hi,

I use pipenv to install autopy3 on win10. An error was occurred while installing. The Python version is 3.6.3.

```
Collecting autopy3
  Using cached autopy3-0.51.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ganzi\AppData\Local\Temp\pip-build-x1976k91\autopy3\setup.py", line 228, in <module>
        EXT_MODULES = create_ext_modules('src/')
      File "C:\Users\ganzi\AppData\Local\Temp\pip-build-x1976k91\autopy3\setup.py", line 186, in create_ext_modules
        raise IOError('windows directory not found at: "%s"' % win_dir)
    OSError: windows directory not found at: "C:\Users\ganzi\AppData\Local\Temp\pip-build-x1976k91\autopy3\windows\win64"

    ----------------------------------------
```

Do someone know how to resolve this problem?

**Comment by chr15stevens** [comment] 2018-01-23 08:25
I'm getting this also, python 3.6. Did you find a fix?

**Comment by fenchu** [comment] 2018-01-29 10:36
Have the same issue,
    `OSError: windows directory not found at: "C:\Users\MORTEN~1.SEN\AppData\Local\Temp\pip-build-p4evz5k1\autopy3\windows\win64"`
- directory 'pip-build-p4evz5k1' does not exists

**Comment by trentbullard** [comment] 2018-02-06 19:17
same, the comments say creates directory structure statically... why is there a check for directory? Shouldn't it just populate the directory structure itself?

**Comment by cryptotvync** [comment] 2018-04-11 02:47
Have the same issue, thought it could be caused by utf in the path, but judging by first comment, it is probably not

**Comment by cryptotvync** [comment] 2018-04-11 03:07
However, you can download an appropriate wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and pip install it

**Comment by gboysen** [comment] 2018-04-11 18:39
Same here neither wheel or tar.gz worked.
I assume it because pip lib is locators in the user ... folder.
Anyone know how to fix that?

**Comment by haydenflinner** [comment] 2018-04-24 00:28
Same error here

**Comment by msanders** [comment] 2018-05-01 22:33
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) which includes binary wheel distributions.

**Closed as completed by msanders** 2018-05-01 22:33 UTC
